mozilla-it/itse-apps-stage-1-infra

terraform/providers.tf
Removing alias from provider since its not needed and only needed if multiple providers exists (aka multiple clusters). The providers were also pointing to the wrong data source so fixing that as well
=> Fix terraform provider to point to the correct module

k8s/workloads/refractr/refractr-ingress.yaml
Switches from using `stable/nginx-ingress` to `ingress-nginx/ingress-nginx` the former package has been consider DEPRECATED so lets move over to something that is maintained
=> Ingress busines

k8s/workloads/refractr/refractr-ingress.yaml, terraform/external-dns.tf
also sneaked in an annotation change for the nlb, just adding an additional tag
=> Setting txtOwnerId for external-dns

terraform/external-dns.tf
Configure `external-dns` to only check `service` as a source. We're removing ingress as a source because it checks
the lists of host in the ingress object and create dns records based on that. This is less than ideal for our
situation
=> Update external-dns to only check for services as a source

k8s/workloads/refractr/refractr-ingress.yaml
This returns the actual IP address of the client instead of the private IP
=> Update externalTrafficPolicy to local

terraform/main.tf, terraform/providers.tf
Jira ticket: https://jira.mozilla.com/browse/SE-1919
* updates terraform module pinned versions to work with updates in [mozilla-it/terraform-modules](https://github.com/mozilla-it/terraform-modules)
~* pins our usage of eks module from [mozilla-it/terraform-modules](https://github.com/mozilla-it/terraform-modules) to a commit so can avoid upstream changes altering us~
=> update tf modules pinned for updates in terraform-modules

terraform/main.tf, terraform/outputs.tf, terraform/providers.tf, terraform/state.tf, terraform/variables.tf, terraform/variables.tfvars
Jira: Came up in context of working on https://mozilla-hub.atlassian.net/browse/SE-1994
note: if you're too busy to review, this can sit. its just cleanup & low-hanging fruit changes while working on this. it would go before the question posed in slack & PRs about terraform structure.
* changes our itse-apps-stage-1 cluster infrastructure to use the AWS terraform providers default_tags; see: https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags
* does some other cleanup (formatting, variable usage, removing duplicated terraform configurations)
Why this PR:
* this is not a priority, but as it was low hanging & not time-consuming fruit during the work for another topic, here it is. if nobody has time to review it, this can sit.
* it gets us better …
=> Use AWS terraform provider default_tags to assign common_tags

k8s/namespaces/pastebin-stage.yaml, k8s/releases/pastebin/pastebin.yaml, k8s/workloads/pastebin/pastebin-ingress.yaml
Jira: https://mozilla-hub.atlassian.net/browse/SE-2103
* deploy pastebin via flux + helmrelease + helm chart into stage cluster
* intention is for pastebin to redeploy to stage whenever the requisite ECR pastebin repo shows a new image with tag format of stg-{seven digit commit sha}
=> Attempt flux + helmrelease deploy of pastebin to stage

k8s/namespaces/moderator-stage.yaml, k8s/releases/moderator/moderator.yaml, k8s/workloads/moderator/moderator-ingress.yaml
Jira: https://mozilla-hub.atlassian.net/browse/SE-2165
* adds kubernetes namespace for moderator-stage 
* adds helmrelease for ingress-nginx for ELB management behind moderator.stage.mozit.cloud, moderator.allizom.org
* adds helmrelease for moderator stage (there will no doubt be some edits here as we change moderator to use releases for CD)
Blocked by: https://github.com/mozilla-it/helm-charts/pull/99
=> Add Moderator Stage namespace, ingress-nginx deploy, helm release

k8s/releases/moderator/moderator.yaml
Jira: Repairs https://mozilla-hub.atlassian.net/browse/SE-2165 based on https://mozilla-hub.atlassian.net/browse/SE-2225
* Adds explicit .Values.image.repository value to Moderator HelmRelease manifest
* Seems that Fluxcd, in order to watch docker images' tags, it needs that image.repository value declared explicitly (can't just be the default in the relevant helm chart values)
* fixed some copypasta from pastebin in the ingress
* fixed configmap to use values required for moderator stage
* fixed secrets to list secrets needed for moderator stage
=> redeclare image.repository default in helmrelease for moderator, moderator config repairs

k8s/releases/moderator/moderator.yaml, terraform/applications/moderator/domain.tf, terraform/applications/moderator/state.tf, terraform/applications/moderator/variables.tf, terraform/applications/moderator/variables.tfvars, terraform/shared/outputs.tf
Jira: https://mozilla-hub.atlassian.net/browse/SE-2165
* remote moderator.stage.mozit.cloud route53 management from terraform, and instead entirely leverage external-dns (e.g. via k8s)
* update mozmoderator helmrelease to reflect helmchart with no commands arg
* remove MOZILLIANS_API_* values (see https://github.com/mozilla-it/helm-charts/pull/111)
=> some repairs to infra to get moderator helmrelease working

k8s/workloads/moderator/moderator-ingress.yaml
see #86 
Believe this is now repaired by https://github.com/mozilla/mozmoderator/pull/357
=> remove special logging for moderator ingress nginx testing

k8s/releases/discourse/discourse-dev.yaml, k8s/releases/discourse/discourse-stage.yaml, terraform/applications/discourse/iam.tf
Jira: https://mozilla-hub.atlassian.net/browse/SE-2169
Blocker: https://github.com/mozilla-it/helm-charts/pull/115
* removes (from state; leaves for clean up after old cluster gone) discourse_role resource from discourse application infra
* gives discourse uploads bucket s3 permissions to cluster nodegroup role (to be refined later)
* Removes `deployment.arn_role` value from the Discourse application helmrelease & updates helm chart to use what is in blocker PR
* we're doing this because it expects kube2iam, which isn't a given on new EKS clusters
=> update discourse helmreleases & application infrastructure to not expect kube2iam / use specific discourse IAM role

k8s/workloads/refractr/refractr-ingress.yaml
It seems like refractr is generating tons of high cardinality metrics
disabling scraping to keep from tipping over the prometheus instance in the cluster
=> Ask prometheus to not scrape refractr

k8s/namespaces/etherpad-stage.yaml, k8s/releases/etherpad/etherpad.yaml, k8s/workloads/etherpad/etherpad-ingress.yaml, k8s/workloads/etherpad/etherpad-oidc.yaml
Jira: https://mozilla-hub.atlassian.net/browse/SE-1151
* adds Etherpad helmrelease deploy setup
* adds Etherpad stage namespace
* adds Etherpad stage ingress-nginx release
* adds Etherpad OIDC gateway release
~Blocked by: https://github.com/mozilla-it/helm-charts/pull/116~
=> Add Etherpad Deploy Setup for Stage (Kubernetes)

k8s/workloads/etherpad/etherpad-ingress.yaml
Jira: cleanup for https://mozilla-hub.atlassian.net/browse/SE-2125
* removes external-dns annotation for pad.allizom.org since we don't need to delegate this domain to AWS for anything, thus just need a CNAME in Infoblox pointing to pad.stage.mozit.cloud
=> remove pad.allizom.org from external-dns config, just need cname for etherpad

terraform/applications/careers/locals.tf, terraform/applications/careers/static.tf
Renaming ACL to reflect the rule
Looking up zone_id for the dns zone, so we can use a human readable name instead of a magic string
=> Collecting a few review comments

terraform/applications/discourse/iam.tf, terraform/shared/outputs.tf
This is the same change I pushed to https://github.com/mozilla-it/itse-apps-prod-1-infra/pull/71.
=> Get IAM worker role name directly from module outputs.

terraform/applications/securitywiki/efs.tf, terraform/applications/securitywiki/providers.tf, terraform/shared/outputs.tf
Jira: https://mozilla-hub.atlassian.net/browse/SE-2159
* updates SecurityWiki EFS to be in the primary eks security group, not the ("additional") eks security group
* fixes SecurityWiki pods talking to EFS over a NFS network connection
Note:
* came up in repairing this - the manually added old security group ids will be removed once this app is migrated
* tagging @duallain on this since he paired with me on it, but happy to walk anyone through what is going on here
=> securitywiki EFS security group updates

k8s/namespaces/securitywiki-stage.yaml, k8s/releases/securitywiki/securitywiki.yaml, k8s/workloads/securitywiki/securitywiki-ingress.yaml
Jira: https://mozilla-hub.atlassian.net/browse/SE-2160
* adds k8s config for securitywiki stage namespace
* adds helmrelease for securitywiki stage ingress-nginx
* adds helmrelease for securitywiki stage application helm release (blocked by helm release pr)
Blocked by: https://github.com/mozilla-it/helm-charts/pull/120
=> Add SecurityWiki Stage Helm Releases

terraform/applications/securitywiki/efs.tf
Jira: https://mozilla-hub.atlassian.net/browse/SE-2163
* removes old, hard-coded security groups from securitywiki EFS mount
=> remove hard coded old securitygroups on secwiki

k8s/releases/discourse/discourse-dev.yaml, k8s/releases/discourse/discourse-stage.yaml, terraform/applications/discourse/secrets.tf
Jira: https://mozilla-hub.atlassian.net/browse/SE-2173 
* replaces the hard-coded logger config ConfigMap template with an ExternalSecrets setup (update discourse helm chart, add secret metadata to terraform for discourse dev, stage logger secret)
* came up in decommissioning https://github.com/mozilla-it/discourse-infra
Related to: https://github.com/mozilla-it/helm-charts/pull/121
=> update discourse dev, stage to use latest helm chart with logger config as secret

k8s/releases/discourse/discourse-dev.yaml, k8s/releases/discourse/discourse-stage.yaml
See https://github.com/mozilla-it/helm-charts/pull/122 - I just inverted key & name in the externalsecrets spec. Caught it in dev & stage testing first, so need to fix here too.
=> uptick helm chart version due to key-value inversion

k8s/releases/discourse/discourse-dev.yaml, k8s/releases/discourse/discourse-stage.yaml, k8s/releases/etherpad/etherpad.yaml, k8s/releases/pastebin/pastebin.yaml, k8s/releases/refractr/refractr.yaml
[SE-3220](https://mozilla-hub.atlassian.net/browse/SE-3220)
Add PodDisruptionBudget apps on k8s to be upgraded.
apps: discourse, etherpad, pastebin, refractr
=> chore: Update chart version for discourse, etherpad, pastebin, refractr

k8s/releases/discourse/discourse-dev.yaml, k8s/releases/discourse/discourse-stage.yaml, k8s/releases/etherpad/etherpad.yaml, k8s/releases/moderator/moderator.yaml, k8s/releases/pastebin/pastebin.yaml, k8s/workloads/discourse/discourse-ingress-dev.yaml, k8s/workloads/discourse/discourse-ingress-stage.yaml, k8s/workloads/etherpad/etherpad-ingress.yaml, k8s/workloads/moderator/moderator-ingress.yaml, k8s/workloads/pastebin/pastebin-ingress.yaml, k8s/workloads/refractr/refractr-ingress.yaml
These changes do the following:
- Setup ingress class configurations per app.
- Update `nginx-ingress` version to 4.2.0
- Adjust `nginx-ingress` to use its app ingress class.
=> Update ingress configs for discourse, etherpad, moderator, pastebin

terraform/applications/discourse/variables.tf
the RDS engine variable was 10  in the variables.tf and the engine version on the console is 14.7
=> fix the rds engine version
