mozilla-it/itse-apps-stage-1-infra

- k8s/releases/refractr/refractr.yaml
- k8s/workloads/refractr/refractr-ingress.yaml
Related to https://github.com/mozilla-it/helm-charts/pull/49 this creates an ingress controller via a helmrelease
> Create ingress controller here

- terraform/cert-manager.tf
Automation to install CRD for cert-manager, this removes the need for us to have it installed by hand
> Auto install CRD

- terraform/main.tf
- terraform/outputs.tf
Adding additional eip outputs and fixed some tags
> Adding additional outputs

- k8s/workloads/refractr/refractr-ingress.yaml
- terraform/external-dns.tf
- terraform/main.tf
Added external DNS helm chart and annotated the service to include the correct hostname
Also sneaked in some upstream terraform changes
> Add external DNS helm chart

- k8s/workloads/refractr/refractr-ingress.yaml
> Fixing annotations

- k8s/releases/refractr/refractr.yaml
Bump chart version to latest version
> Update chart version and fix issuer values

- .secrets.baseline
- k8s/releases/refractr/refractr.yaml
- k8s/workloads/refractr/refractr-ingress.yaml
- terraform/cert-manager.tf
Also sneaked in some changes to cert manager and ingress-controller
> Refractr chart bump

- k8s/releases/refractr/refractr.yaml
Dependent on https://github.com/mozilla-it/helm-charts/pull/58 being merged
> Bump refractr chart

- k8s/releases/refractr/refractr.yaml
Dependent on https://github.com/mozilla-it/helm-charts/pull/63 being merged
> Bump Chart

- k8s/releases/refractr/refractr.yaml
When I said 1.16 I really meant 1.15
> Version typo

- k8s/workloads/grafana/grafana.yml
Working deploy
Only has local to cluster service
example/wip dashboard for refactr
> Initial Grafana Deploy

- k8s/workloads/grafana/grafana.yml
Making variables be recomputed on dashboard load
making the window of time be reflected in graphs (now shows total requests over 6 hours if you pick 6 hour range)
> Some small adjustments to refactr dashboard

- terraform/cert-manager.tf
This fixes an issue where the `cert-manager` pod was unable to extract the role information to make changes to route53
> Fixing cert manager irsa role

- terraform/main.tf
With PR https://github.com/mozilla-it/terraform-modules/pull/131 merged we need to add back the default node now
> Add default node

- .pre-commit-config.yaml
- .secrets.baseline
Just bumping precommit version
> Updating precommit

- .github/workflows/tf-lint.yaml
- k8s/releases/pastebin/pastebin.yaml
See https://github.com/mozilla-it/helm-charts/pull/98
> Update pastebin app helmrelease for patch of yaml error

- k8s/releases/pastebin/pastebin.yaml
Final one I'm hoping to close https://mozilla-hub.atlassian.net/browse/SE-2103
> have pastebin stage app use lets encrypt prod

- k8s/releases/pastebin/pastebin.yaml
Bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1721350
Jira ticket: https://mozilla-hub.atlassian.net/browse/SE-2225
Why this PR:
* Need to deploy a bug fix for pastebin stage
* Flux currently not working for PAstebin stage docker image changes
> change image tag for stage pastebin

- k8s/releases/pastebin/pastebin.yaml
Jira: https://mozilla-hub.atlassian.net/browse/SE-2225
Testing one possible repair
> try explicitly adding image repo to pastebin helmrelease for flux

- k8s/workloads/moderator/moderator-ingress.yaml
> Nginx logging

- k8s/workloads/moderator/moderator-ingress.yaml
> remove proxy-protocol (broke the app), go back to enable-real-ip

- k8s/workloads/moderator/moderator-ingress.yaml
> enable real-ip & forward-headers

- k8s/workloads/moderator/moderator-ingress.yaml
> expanding logging to try to figure out nginx remote_addr

- k8s/workloads/moderator/moderator-ingress.yaml
> altering logging to pin down proxy settings & forwarded headers mixup

- terraform/shared/main.tf
Pulls from external secret to export data to Influxdb
Example of data now showing up.
> SE-2452 Export prometheus to influxdb

- k8s/namespaces/careers-stage.yaml
- k8s/releases/careers/careers-stage.yaml
- k8s/workloads/careers/careers-ingress-stage.yaml
Will live at https://careers.stage.mozit.cloud
is a pretty simple web page, and also a fairly simple perodic job to build the website
> Initial deployment of careers staging

- terraform/applications/discourse/.terraform.lock.hcl
- terraform/applications/discourse/cdn.tf
Jira: https://mozilla-hub.atlassian.net/browse/SE-2162
* adds new origins to dev, stage discourse CDN for new cluster apps
* (~possibly in future update after meeting with leo~): remove old origins for old cluster app, as okay with partial decomm
> add new discourse dev, stage domain as origins to respective cdns

- k8s/releases/careers/careers-stage.yaml
- k8s/workloads/careers/careers-ingress-stage.yaml
- terraform/applications/careers/.terraform.lock.hcl
- terraform/applications/careers/lambda-headers.js
- terraform/applications/careers/locals.tf
- terraform/applications/careers/providers.tf
- terraform/applications/careers/state.tf
- terraform/applications/careers/static.tf
s3 bucket
a cert
a cloudfront
and the magic
> Creating the infrastructure needed to host static careers

- k8s/releases/moderator/moderator.yaml
[SE-3220](https://mozilla-hub.atlassian.net/browse/SE-3220)
Add PodDisruptionBudget for mozmoderator app on k8s to be upgraded.
> chore(moderator) Update chart version

- terraform/applications/discourse/psql.tf
- terraform/applications/discourse/variables.tf
> add-ca-cert-identifier-rds-discourse

- terraform/applications/discourse/cdn.tf
- terraform/applications/discourse/email.tf
- terraform/applications/discourse/tldr.tf
- terraform/applications/discourse/uploads.tf
https://registry.terraform.io/providers/hashicorp/aws/3.75.1/docs/resources/s3_bucket_server_side_encryption_configuration#usage-notes
> S3 lifecycle ignore block
